FROM node:20-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm i

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application
CMD sh -c "npx drizzle-kit generate && npx drizzle-kit migrate && npx nodemon --legacy-watch --exec tsx src/index.ts"
