/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthImport } from './routes/_auth'
import { Route as SplatImport } from './routes/$'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedManageUserIndexImport } from './routes/_authenticated/manage-user/index'
import { Route as AuthenticatedLogoutIndexImport } from './routes/_authenticated/logout/index'
import { Route as AuthenticatedEvidenceIndexImport } from './routes/_authenticated/evidence/index'
import { Route as AuthenticatedDashboardIndexImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthLoginIndexImport } from './routes/_auth/login/index'
import { Route as AuthenticatedComplianceStandardImport } from './routes/_authenticated/compliance/$standard'
import { Route as AuthAuthResponseSuccessImport } from './routes/_auth/auth-response/success'
import { Route as AuthAuthResponseNoAccessImport } from './routes/_auth/auth-response/no-access'
import { Route as AuthAuthResponseErrorImport } from './routes/_auth/auth-response/error'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedManageUserIndexRoute =
  AuthenticatedManageUserIndexImport.update({
    id: '/manage-user/',
    path: '/manage-user/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedLogoutIndexRoute = AuthenticatedLogoutIndexImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedEvidenceIndexRoute = AuthenticatedEvidenceIndexImport.update(
  {
    id: '/evidence/',
    path: '/evidence/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthenticatedComplianceStandardRoute =
  AuthenticatedComplianceStandardImport.update({
    id: '/compliance/$standard',
    path: '/compliance/$standard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthAuthResponseSuccessRoute = AuthAuthResponseSuccessImport.update({
  id: '/auth-response/success',
  path: '/auth-response/success',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAuthResponseNoAccessRoute = AuthAuthResponseNoAccessImport.update({
  id: '/auth-response/no-access',
  path: '/auth-response/no-access',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAuthResponseErrorRoute = AuthAuthResponseErrorImport.update({
  id: '/auth-response/error',
  path: '/auth-response/error',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth-response/error': {
      id: '/_auth/auth-response/error'
      path: '/auth-response/error'
      fullPath: '/auth-response/error'
      preLoaderRoute: typeof AuthAuthResponseErrorImport
      parentRoute: typeof AuthImport
    }
    '/_auth/auth-response/no-access': {
      id: '/_auth/auth-response/no-access'
      path: '/auth-response/no-access'
      fullPath: '/auth-response/no-access'
      preLoaderRoute: typeof AuthAuthResponseNoAccessImport
      parentRoute: typeof AuthImport
    }
    '/_auth/auth-response/success': {
      id: '/_auth/auth-response/success'
      path: '/auth-response/success'
      fullPath: '/auth-response/success'
      preLoaderRoute: typeof AuthAuthResponseSuccessImport
      parentRoute: typeof AuthImport
    }
    '/_authenticated/compliance/$standard': {
      id: '/_authenticated/compliance/$standard'
      path: '/compliance/$standard'
      fullPath: '/compliance/$standard'
      preLoaderRoute: typeof AuthenticatedComplianceStandardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof AuthImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/evidence/': {
      id: '/_authenticated/evidence/'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof AuthenticatedEvidenceIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/logout/': {
      id: '/_authenticated/logout/'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthenticatedLogoutIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/manage-user/': {
      id: '/_authenticated/manage-user/'
      path: '/manage-user'
      fullPath: '/manage-user'
      preLoaderRoute: typeof AuthenticatedManageUserIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAuthResponseErrorRoute: typeof AuthAuthResponseErrorRoute
  AuthAuthResponseNoAccessRoute: typeof AuthAuthResponseNoAccessRoute
  AuthAuthResponseSuccessRoute: typeof AuthAuthResponseSuccessRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthResponseErrorRoute: AuthAuthResponseErrorRoute,
  AuthAuthResponseNoAccessRoute: AuthAuthResponseNoAccessRoute,
  AuthAuthResponseSuccessRoute: AuthAuthResponseSuccessRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedComplianceStandardRoute: typeof AuthenticatedComplianceStandardRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedEvidenceIndexRoute: typeof AuthenticatedEvidenceIndexRoute
  AuthenticatedLogoutIndexRoute: typeof AuthenticatedLogoutIndexRoute
  AuthenticatedManageUserIndexRoute: typeof AuthenticatedManageUserIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedComplianceStandardRoute: AuthenticatedComplianceStandardRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedEvidenceIndexRoute: AuthenticatedEvidenceIndexRoute,
  AuthenticatedLogoutIndexRoute: AuthenticatedLogoutIndexRoute,
  AuthenticatedManageUserIndexRoute: AuthenticatedManageUserIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth-response/error': typeof AuthAuthResponseErrorRoute
  '/auth-response/no-access': typeof AuthAuthResponseNoAccessRoute
  '/auth-response/success': typeof AuthAuthResponseSuccessRoute
  '/compliance/$standard': typeof AuthenticatedComplianceStandardRoute
  '/login': typeof AuthLoginIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/evidence': typeof AuthenticatedEvidenceIndexRoute
  '/logout': typeof AuthenticatedLogoutIndexRoute
  '/manage-user': typeof AuthenticatedManageUserIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth-response/error': typeof AuthAuthResponseErrorRoute
  '/auth-response/no-access': typeof AuthAuthResponseNoAccessRoute
  '/auth-response/success': typeof AuthAuthResponseSuccessRoute
  '/compliance/$standard': typeof AuthenticatedComplianceStandardRoute
  '/login': typeof AuthLoginIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/evidence': typeof AuthenticatedEvidenceIndexRoute
  '/logout': typeof AuthenticatedLogoutIndexRoute
  '/manage-user': typeof AuthenticatedManageUserIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/auth-response/error': typeof AuthAuthResponseErrorRoute
  '/_auth/auth-response/no-access': typeof AuthAuthResponseNoAccessRoute
  '/_auth/auth-response/success': typeof AuthAuthResponseSuccessRoute
  '/_authenticated/compliance/$standard': typeof AuthenticatedComplianceStandardRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/evidence/': typeof AuthenticatedEvidenceIndexRoute
  '/_authenticated/logout/': typeof AuthenticatedLogoutIndexRoute
  '/_authenticated/manage-user/': typeof AuthenticatedManageUserIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | ''
    | '/auth-response/error'
    | '/auth-response/no-access'
    | '/auth-response/success'
    | '/compliance/$standard'
    | '/login'
    | '/dashboard'
    | '/evidence'
    | '/logout'
    | '/manage-user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | ''
    | '/auth-response/error'
    | '/auth-response/no-access'
    | '/auth-response/success'
    | '/compliance/$standard'
    | '/login'
    | '/dashboard'
    | '/evidence'
    | '/logout'
    | '/manage-user'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/auth-response/error'
    | '/_auth/auth-response/no-access'
    | '/_auth/auth-response/success'
    | '/_authenticated/compliance/$standard'
    | '/_auth/login/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/evidence/'
    | '/_authenticated/logout/'
    | '/_authenticated/manage-user/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$",
        "/_auth",
        "/_authenticated"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$": {
      "filePath": "$.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auth-response/error",
        "/_auth/auth-response/no-access",
        "/_auth/auth-response/success",
        "/_auth/login/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/compliance/$standard",
        "/_authenticated/dashboard/",
        "/_authenticated/evidence/",
        "/_authenticated/logout/",
        "/_authenticated/manage-user/"
      ]
    },
    "/_auth/auth-response/error": {
      "filePath": "_auth/auth-response/error.tsx",
      "parent": "/_auth"
    },
    "/_auth/auth-response/no-access": {
      "filePath": "_auth/auth-response/no-access.tsx",
      "parent": "/_auth"
    },
    "/_auth/auth-response/success": {
      "filePath": "_auth/auth-response/success.tsx",
      "parent": "/_auth"
    },
    "/_authenticated/compliance/$standard": {
      "filePath": "_authenticated/compliance/$standard.tsx",
      "parent": "/_authenticated"
    },
    "/_auth/login/": {
      "filePath": "_auth/login/index.tsx",
      "parent": "/_auth"
    },
    "/_authenticated/dashboard/": {
      "filePath": "_authenticated/dashboard/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/evidence/": {
      "filePath": "_authenticated/evidence/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/logout/": {
      "filePath": "_authenticated/logout/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/manage-user/": {
      "filePath": "_authenticated/manage-user/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
